[package]
name = "laythe_env"
version = "0.1.0"
authors = ["John Chabot <johnchabot2013@gmail.com>"]
edition = "2021"

[lib]
name = "laythe_env"
path = "src/lib.rs"

[dependencies]
hashbrown = "0.14.5"
fnv = "1.0.7"
termcolor = "1.4.1"