[package]
name = "laythe_env"
version = "0.1.0"
authors = ["John Chabot <johnchabot2013@gmail.com>"]
edition = "2018"

[lib]
name = "laythe_env"
path = "src/lib.rs"

[features]
debug_gc = []
debug_stress_gc = []

[dependencies]
hashbrown = "0.9.1"
fnv = "1.0.3"
rayon = "1.5.0"