[workspace]
members = [
  "spacelox_compiler_bench",
  "spacelox_core",
  "spacelox_lib",
  "spacelox_macro",
  "spacelox_vm",
  "spacelox_wasm",
  "spacelox",
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
debug = true
