[package]
name = "laythe_lib"
version = "0.1.0"
authors = ["John Chabot <johnchabot2013@gmail.com>"]
edition = "2018"

[lib]
name = "laythe_lib"
path = "src/lib.rs"

[dependencies]
laythe_core = { path = "../laythe_core" } # , features = ["nan_boxing"]
laythe_env = { path = "../laythe_env" }
hashbrown = "0.7.2"
fnv = "1.0.3"

[dev-dependencies]
criterion = "0.3"