[package]
name = "laythe_macro"
version = "0.1.0"
authors = ["John Chabot <johnchabot2013@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true
name = "laythe_macro"
path = "src/lib.rs"

[dependencies]
proc-macro2 = "1.0.12"
quote = "1.0.4"
syn = "1.0.18"