[package]
name = "laythe_native"
version = "0.1.0"
authors = ["John Chabot <johnchabot2013@gmail.com>"]
edition = "2018"

[lib]
name = "laythe_native"
path = "src/lib.rs"

[dependencies]
laythe_env = { path = "../laythe_env" }
