[package]
name = "spacelox_core"
version = "0.1.0"
authors = ["John Chabot <johnchabot2013@gmail.com>"]
edition = "2018"

[lib]
name = "spacelox_core"
path = "src/lib.rs"

[features]
debug = []

[dependencies]
fnv = "1.0.3"

