[package]
name = "spacelox_env"
version = "0.1.0"
authors = ["John Chabot <johnchabot2013@gmail.com>"]
edition = "2018"

[lib]
name = "spacelox_env"
path = "src/lib.rs"

[features]
debug_gc = []
debug_stress_gc = []

[dependencies]
spacelox_macro = { path = "../spacelox_macro" }
hashbrown = "0.7.2"